name: kaufes
description: mobile application
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.14.0
  firebase_auth: ^4.1.4
  google_sign_in: ^5.4.2
  flutter_svg: ^2.0.5
  loading_indicator: ^3.1.0
  flutter_spinkit: ^5.2.0
  easy_localization: ^3.0.2
  dio: ^5.2.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_messaging: ^14.6.4
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^5.0.11
  flutter_google_places_sdk: ^0.3.2+9
  change_app_package_name: ^1.1.0
  flutter_typeahead: ^4.6.2
  flutter_keyboard_visibility: ^5.4.1
  cached_network_image: ^3.2.3
  infinite_scroll_pagination: ^3.2.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  google_maps_flutter: ^2.3.0
  url_launcher: ^6.1.11
  image_picker: ^1.0.0
  csc_picker: ^0.2.7
  flutter_web_auth: ^0.5.0
  google_fonts: ^4.0.4
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/other_images/
    - assets/translations/
    - assets/flags/


  